name: GiveAdminTools
version: '${project.version}'
main: me.melarnoff.giveadmintools.GiveAdminTools
api-version: 1.19
commands:
  kickbedrock:
    description: Gives a player a kick stick
  ogogomech:
    description: Gives a player a very sharp sword
  mutestick:
    description: Gives a player a stick, which can mute a mob by clicking on it